### ISSUE TITLE
Also works with missing }

### ISSUE THREAD

**Issue by obromios** [zombocom/syntax_search#18]
Although it is kind of obvious, I was delighted to see this also picks up missing braces i.e

`a = ary.map {|x| x**2 `

It might be worth mentioning this in the Readme.

This would have saved me hours of frustration when I was first learning ruby, and even today, it will still save time, so thank  you very much.   Hope it ends up in standard ruby. 

It would be great if someone put this code into the common editors, e.g. Sublime Text Linter.

**Comment by mapreal19** [comment]
This can't go into rubocop?

**Comment by schneems** [comment]
> This would have saved me hours of frustration when I was first learning ruby, and even today, it will still save time, so thank you very much. Hope it ends up in standard ruby.

Great! There's still some sharp edges that hopefully can be worked out. Namely output for large files is really unwieldy and there's a few indentation patterns that are reasonable that we should better support. Thanks for trying it out!


> This can't go into rubocop?

Assuming "this" is this library? I think rubocop would error on this as it's not parseable, but I've no idea what it would do with it. I think probably just give you the same error ruby gives.

**Comment by schneems** [comment]
As a side note, that this works is kind-of an accident.

```
$ syntax_search bad.rb

SyntaxSearch: Missing `end` detected

This code has a missing `end`. Ensure that all
syntax keywords (`def`, `do`, etc.) have a matching `end`.

file: /private/tmp/2314b597165519808e4b1d8a07b3129c/bad.rb
simplified:

    ❯ 1  Array().each {|foo| foo += 2

⛄ 2.7.2 🚀  /tmp/2314b597165519808e4b1d8a07b3129c
$ ruby -wc bad.rb
bad.rb:1: syntax error, unexpected end-of-input, expecting '}'
```

I didn't realize that `unexpected end-of-input` could be generated via other methods (though it makes total sense), but I'm glad the current solution is generic enough to handle this case :)

**Comment by obromios** [comment]
Good software engineering on your part.

By a strange coincidence, right now I am learning the syntax for Arduino language (a C++ dialect), and just spent 10 minutes struggling with exactly this problem (a missing '}' causing a long syntax error at an unrelated place).  Looks like this could be of use in other languages.

**Comment by mapreal19** [comment]
@schneems Just tried and this is what you get:

![image](https://user-images.githubusercontent.com/3055997/101647960-a1617e00-3a39-11eb-9902-72950f65838c.png)

I wonder if it was possible to include it on rubocop via an extension (sorry, I should have posted this in another issue)

**Comment by schneems** [comment]
I'm updating the message to show we have explicit support for `|` and `}` as well as `end` https://github.com/zombocom/syntax_search/pull/29
